spring.application.name=Review de Livro

#Database Configuração
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
